config/routes.rb
Rails.application.routes.draw do
  get '/' => 'rails_objects#index'

  resources :rails_objects
end

app/models/rails_object.rb
class RailsObject < ActiveRecord::Base
end

app/controllers/api/angular_data_controller.rb
class Api::AngularDataController < ApplicationController
  before_action :set_rails_object, only: [:show, :edit, :update, :destroy]

  # GET /rails_objects
  # GET /rails_objects.json
  def index
    @rails_objects = RailsObject.all
  end

  # GET /rails_objects/1
  # GET /rails_objects/1.json
  def show
  end

  # GET /rails_objects/new
  def new
    @rails_object = RailsObject.new
  end

  # GET /rails_objects/1/edit
  def edit
  end

  # POST /rails_objects
  # POST /rails_objects.json
  def create
    @rails_object = RailsObject.new(rails_object_params)

    respond_to do |format|
      if @rails_object.save
        format.html { redirect_to @rails_object, notice: 'Rails object was successfully created.' }
        format.json { render :show, status: :created, location: @rails_object }
      else
        format.html { render :new }
        format.json { render json: @rails_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rails_objects/1
  # PATCH/PUT /rails_objects/1.json
  def update
    respond_to do |format|
      if @rails_object.update(rails_object_params)
        format.html { redirect_to @rails_object, notice: 'Rails object was successfully updated.' }
        format.json { render :show, status: :ok, location: @rails_object }
      else
        format.html { render :edit }
        format.json { render json: @rails_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rails_objects/1
  # DELETE /rails_objects/1.json
  def destroy
    @rails_object.destroy
    respond_to do |format|
      format.html { redirect_to rails_objects_url, notice: 'Rails object was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rails_object
      @rails_object = RailsObject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rails_object_params
      params.fetch(:rails_object, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rails_objects_controller.rb
class RailsObjectsController < ApplicationController
  before_action :set_rails_object, only: [:show, :edit, :update, :destroy]

  # GET /rails_objects
  # GET /rails_objects.json
  def index
    @rails_objects = RailsObject.all
  end

  # GET /rails_objects/1
  # GET /rails_objects/1.json
  def show
  end

  # GET /rails_objects/new
  def new
    @rails_object = RailsObject.new
  end

  # GET /rails_objects/1/edit
  def edit
  end

  # POST /rails_objects
  # POST /rails_objects.json
  def create
    @rails_object = RailsObject.new(rails_object_params)

    respond_to do |format|
      if @rails_object.save
        format.html { redirect_to @rails_object, notice: 'Rails object was successfully created.' }
        format.json { render :show, status: :created, location: @rails_object }
      else
        format.html { render :new }
        format.json { render json: @rails_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rails_objects/1
  # PATCH/PUT /rails_objects/1.json
  def update
    respond_to do |format|
      if @rails_object.update(rails_object_params)
        format.html { redirect_to @rails_object, notice: 'Rails object was successfully updated.' }
        format.json { render :show, status: :ok, location: @rails_object }
      else
        format.html { render :edit }
        format.json { render json: @rails_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rails_objects/1
  # DELETE /rails_objects/1.json
  def destroy
    @rails_object.destroy
    respond_to do |format|
      format.html { redirect_to rails_objects_url, notice: 'Rails object was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rails_object
      @rails_object = RailsObject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rails_object_params
      params.require(:rails_object).permit(:firstName, :lastName, :gender)
    end
end

app/helpers/api/angular_data_helper.rb
module Api::AngularDataHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rails_objects_helper.rb
module RailsObjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAPIAngularjs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="angularApiApp">

<%= yield %>

</body>
</html>

app/views/rails_objects/_form.html.erb
<%= form_for(@rails_object) do |f| %>
  <% if @rails_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rails_object.errors.count, "error") %> prohibited this rails_object from being saved:</h2>

      <ul>
      <% @rails_object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName, "First Name" %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName, "Last Name" %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rails_objects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rails Objects</h1>

<div class="angularExample">
  <div class="scopeVariable">
    Hello
    <span ng-if="name" ng-bind="name"></span> !!!
  </div>
Enter your name: <input type="text" ng-model="name"><br/>
View the result Instantly! above. 
</div>

<table class="table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rails_objects.each do |rails_object| %>
      <tr>
        <td><%= rails_object.firstName %></td>
        <td><%= rails_object.lastName %></td>
        <td><%= rails_object.gender %></td>
        <td><%= link_to 'Show', rails_object %></td>
        <td><%= link_to 'Edit', edit_rails_object_path(rails_object) %></td>
        <td><%= link_to 'Destroy', rails_object, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rails object', new_rails_object_path %>

app/views/rails_objects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @rails_object.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @rails_object.lastName %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @rails_object.gender %>
</p>

<%= link_to 'Edit', edit_rails_object_path(@rails_object) %> |
<%= link_to 'Back', rails_objects_path %>